var fs=require('fs');
var c=fs.readFileSync('C:\\Users\\sport\\Documents\\MyHeroUltraTuning\\png_gen.js','utf8');

var oldSpec = '    var specH=84,specW=Math.floor((rw-12)/2),specGap=12;\n\n    for(var si=0;si<2;si++){\n      var ss=ST.specs[si];\n      var sx=rx+si*(specW+specGap);\n      rr(sx,stY+28,specW,specH,8,\'#111827\',\'rgba(167,139,250,.15)\');\n      if(ss&&ss.tid){\n        var se=findSpecial(ss.tid);\n        if(se){\n          var rc4=RC[se.role]||\'#94a3b8\';\n          ctx.fillStyle=rc4;ctx.fillRect(sx+2,stY+34,3,specH-12);\n          ctx.fillStyle=\'#6b7280\';ctx.font=\'bold 13px Rajdhani,sans-serif\';\n          ctx.fillText(si===0?\'LEFT\':\'RIGHT\',sx+10,stY+46);\n          // Role badge with H/V\n          var specRoleText=se.role||\'SPEC\';\n          if(se.align)specRoleText+=\' \'+(se.align===\'hero\'?\'H\':\'V\');\n          bdg(sx+50,stY+34,specRoleText,rc4,11);\n          // Skill name\n          ctx.fillStyle=\'#f1f5f9\';ctx.font=\'bold 15px Rajdhani,sans-serif\';\n          var sn=se.skillName||se.name||\'\';if(sn.length>28)sn=sn.substring(0,28)+\'...\';\n          ctx.fillText(sn,sx+10,stY+62);\n          // Description\n          ctx.fillStyle=\'#94a3b8\';ctx.font=\'12px Rajdhani,sans-serif\';\n          var sd2=se.effect||se.desc||\'\';if(sd2.length>42)sd2=sd2.substring(0,42)+\'...\';\n          ctx.fillText(sd2,sx+10,stY+78);\n          // Level text (no bar)\n          var mxLv=cos&&cos.ra===\'PUR\'?11:5;\n          ctx.fillStyle=\'#e2e8f0\';ctx.font=\'bold 12px Rajdhani,sans-serif\';ctx.textAlign=\'right\';\n          ctx.fillText(\'Lv. \'+(ss?ss.lv:1)+\'/\'+mxLv,sx+specW-10,stY+46);ctx.textAlign=\'left\');\n          // Special tuning icon (not character portrait)\n          if(specIcons[ss.tid])circ(sx+specW-46,stY+34,38,specIcons[ss.tid],rc4);\n          else if(se.chara&&slotImgs[se.chara])circ(sx+specW-46,stY+34,38,slotImgs[se.chara],rc4);\n        }\n      }\n    }';

var newSpec = '    var specH=100,specW=Math.floor((rw-12)/2),specGap=12;\n\n    for(var si=0;si<2;si++){\n      var ss=ST.specs[si];\n      var sx=rx+si*(specW+specGap);\n      rr(sx,stY+28,specW,specH,8,\'#111827\',\'rgba(167,139,250,.15)\');\n      if(ss&&ss.tid){\n        var se=findSpecial(ss.tid);\n        if(se){\n          var rc4=RC[se.role]||\'#94a3b8\';\n          ctx.fillStyle=rc4;ctx.fillRect(sx+2,stY+34,3,specH-12);\n          // LEFT/RIGHT label\n          ctx.fillStyle=\'#6b7280\';ctx.font=\'bold 12px Rajdhani,sans-serif\';\n          ctx.fillText(si===0?\'LEFT\':\'RIGHT\',sx+10,stY+44);\n          // Role badge with H/V\n          var specRoleText=se.role||\'SPEC\';\n          if(se.align)specRoleText+=\' \'+(se.align===\'hero\'?\'H\':\'V\');\n          bdg(sx+52,stY+34,specRoleText,rc4,11);\n          // Skill name — below badge row\n          ctx.fillStyle=\'#f1f5f9\';ctx.font=\'bold 15px Rajdhani,sans-serif\';\n          var sn=se.skillName||se.name||\'\';if(sn.length>30)sn=sn.substring(0,30)+\'...\';\n          ctx.fillText(sn,sx+10,stY+62);\n          // Description\n          ctx.fillStyle=\'#94a3b8\';ctx.font=\'12px Rajdhani,sans-serif\';\n          var sd2=se.effect||se.desc||se.skillDesc||\'\';if(sd2.length>44)sd2=sd2.substring(0,44)+\'...\';\n          ctx.fillText(sd2,sx+10,stY+78);\n          // Level — below description\n          var mxLv=cos&&cos.ra===\'PUR\'?11:5;\n          ctx.fillStyle=\'#e2e8f0\';ctx.font=\'bold 12px Rajdhani,sans-serif\';\n          ctx.fillText(\'Lv. \'+(ss?ss.lv:1)+\'/\'+mxLv,sx+10,stY+94);\n          // Special tuning icon — right side, no outline\n          if(specIcons[ss.tid])circ(sx+specW-48,stY+34,38,specIcons[ss.tid]);\n          else if(se.chara&&slotImgs[se.chara])circ(sx+specW-48,stY+34,38,slotImgs[se.chara]);\n        }\n      }\n    }';

if(c.indexOf(oldSpec)!==-1){
  c=c.replace(oldSpec,newSpec);
  fs.writeFileSync('C:\\Users\\sport\\Documents\\MyHeroUltraTuning\\png_gen.js',c);
  console.log('Fixed special tuning section');
}else{
  console.log('ERROR: old string not found');
}
